example.com:
  layer: "bottom"  # (str) "bottom"|"top"
  backend: "cloudflare"  # (str) "cloudflare"|"dnspod"
  auth:
    token: "your_token"  # token for clouflare, secret_id and secret_key for dnspod
  hosts:
    - name: "your_host_name_v0"  # (str) hostname
      addresses:  # (optional[dict|list|str]) addresses. if str or list, assuming zone = 0
        0: ["your_host_ip4", "your_host_ip6"]  # zone 0: native addresses
        1: ["your_tunnel_ip4", "your_tunnel_ip6"]  # zone 1: proxied or tunnel addresses
        10: ~  # zone 10: managed by other means such as ddns
        42: ["your_other_addr"]  # zones id > 9 are custom zones.
      mid_names:  # (list[dict]|list[str]|str) middle-layer name/names. if str, assuming current = false.
        - name: "the_name"  # (str) middle-layer name. if ends with "-v...", it will be treated as a normal presentation name and converted to multiple varied presentations (e.g., "cn0-v0" -> [ "cn0-v0", "cn0-v0-ext", "cn0-v0-ip4", "cn0-v0-ip6", "cn0-v0-42"]). otherwise, it will be treated as a network name without any variation.
          current: false  # (optional) only when presentation name ends with "-v...", it will be treated as the current presentation, e.g., "cn0-v0" -> "cn0".
          current_zone: 0  # (optional) this defines which variation is used, e.g., setting 4 will use "cn0-v0-ip4" or "xxxxx.0" as the current presentation.

example.net:
  layer: "top"
  bottom: "example.com"  # (optional[str]) bottom-layer domain name. all records not ending with a dot will be appended with this domain name.
  backend: "dnspod"
  auth:
    secret_id: "your_secret_id"
    secret_key: "your_secret_key"
  domains:
    - names: [ "www", "blog", "@" ]  # (list|str) subdomain names. they will have the same record content.
      records:  # (list[dict]|str)
        - value: "a.com"  # A,AAAA,CNAME auto-detected
          line: "境内"  # (optional) resolve line, only available for dnspod
        - value: "1.1.1.1"
          line: "境外"
      cnames: [ "tools", "man" ]  # (optional[list|str]) canonical names. here, subdomains "tools" and "man" are canonicalized to "www".
